services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}   
    ports:
      - 5000:5000
    volumes:
      - ${DATADIR}/kavita/config:/config
      - ${MEDIADIR}/Books:/books
      - ${MEDIADIR}/Comics:/comics
      - ${MEDIADIR}/Manga:/manga
    restart: unless-stopped
    networks:S
      - frontend

networks:
  frontend:
    name: frontend
    external: true
