#https://nginxproxymanager.com/guide/

services:
  nginxproxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ${DATADIR}/nginxproxymanager/data:/data
      - ${DATADIR}/nginxproxymanager/letsencrypt:/etc/letsencrypt
