# https://docs.linuxserver.io/images/docker-plex/
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ${DATADIR}/plex/config:/config
      - {MEDIADIR}:/Valkyrie
      - {MEDIADIR1}:/Ironwolf
    restart: unless-stopped
    
