# https://docs.linuxserver.io/images/docker-plex/
# port 32400/web

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ${DATADIR}/plex/config:/config
      - ${MEDIADIR}:/Valkyrie
      - ${MEDIADIR1}:/Ironwolf
    restart: unless-stopped
    devices:
      - "/dev/dri/card0:/dev/dri/card0"
      - "/dev/dri/renderD128:/dev/dri/renderD128"
