services:
  mstream:
    image: lscr.io/linuxserver/mstream:latest
    container_name: mstream
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${DATADIR}/mstream/config:/config
      - ${MEDIADIR}/Music:/music
    ports:
      - 3300:3000
    restart: unless-stopped