name: audiobookshelf
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    ports:
      - 2080:80
    volumes:
      - ${MEDIADIR}/Audiobooks:/audiobooks
      - ${DATADIR}/audiobookshelf/config:/config
      - ${DATADIR}/audiobookshelf/metadata:/metadata
      - /etc/localtime:/etc/localtime:ro
    networks:
      - frontend
networks:
  frontend:
    name: frontend
    external: true
